FROM python:3.11-slim
WORKDIR /app
COPY src/qexe/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/qexe/app /app/app
ENV PYTHONUNBUFFERED=1
EXPOSE 8081
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8081"]
